version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 20
    groups:
      java-dependencies:
        patterns: ['*']

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
